import SideBar from "@/components/SideBar";
import { StackProvider, StackTheme } from "@stackframe/stack";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { stackServerApp } from "../stack";
import "./globals.css";



const dm = DM_Sans({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm.className} antialiased`}
      >
        <StackProvider app={stackServerApp}>
          <StackTheme>
            <div className="flex items-center justify-between w-full">
              <SideBar />
              <div className="w-4/5">
                {children}

              </div>
            </div>
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
